apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "fullname" . }}
  namespace: {{ .Values.global.clusterNamespace }}
data:
  log_level: {{ index .Values.global.log_level .Values.global.env | quote }}
  shardId: {{ .Values.global.shardId | quote }}
  shardData: {{ .Values.global.shardData | quote }}
