apiVersion: v1
kind: Service
metadata:
  name: {{ template "fullname" . }}
  namespace: {{ .Values.global.clusterNamespace }}
  labels:
     microservice: {{ .Values.global.name }}
spec:
  ports:
    - port: 9002
      name: accapi
      targetPort: 9002
  selector:
    app: configmgr
