apiVersion: extensions/v1beta1
kind: Deployment
metadata:
   name: {{ template "fullname" . }}
   namespace: {{ .Values.global.clusterNamespace }}
spec:
   revisionHistoryLimit: 10
   minReadySeconds: 10
   strategy:
      type: RollingUpdate
      rollingUpdate:
         maxUnavailable: 0
         maxSurge: 3
   replicas: 1
   template:
      metadata:
         labels:
            microservice: {{ .Values.global.name }}
            app: configmgr
      spec:
         imagePullSecrets:
         - name: my-secret
         containers:
         - name: {{ .Values.global.name }}
           image: {{ .Values.global.registry | default "registry.ng.bluemix.net" }}/{{ .Values.global.registryNamespace }}/{{ .Values.global.name }}:{{ .Values.global.tag | default "last" }}
           ports:
           - containerPort: 9002
           env:
           - name: LOG_LEVEL
             valueFrom:
               configMapKeyRef:
                  name: {{ template "fullname" . }}-configuration
                  key: log_level
           - name: shardId
             valueFrom:
               configMapKeyRef:
{{- if .Values.global.autoConfig }}
                  name: {{ .Values.global.autoConfigName }}
{{- else }}
                  name: {{ template "fullname" . }}-configuration
{{- end }}
                  key: shardId
           - name: shardData
             valueFrom:
               configMapKeyRef:
{{- if .Values.global.autoConfig }}
                  name: {{ .Values.global.autoConfigName }}
{{- else }}
                  name: {{ template "fullname" . }}-configuration
{{- end }}
                  key: shardData
