apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ template "minio.fullname" . }}
  namespace: "{{.Release.Namespace}}"
spec:
   rules:
   - http:
      paths:
      - path: /
        backend:
          serviceName: {{ template "minio.fullname" . }}
          servicePort: 9000


