apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ .Values.minio.fullnameOverride | quote }}
  namespace: "{{.Release.Namespace}}"
spec:
   rules:
   - http:
      paths:
      - path: /
        backend:
          serviceName: {{ .Values.minio.fullnameOverride | quote }}
          servicePort: 9000


