apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ template "minio.fullname" .Values.minio }}
  namespace: "{{.Release.Namespace}}"
spec:
   rules:
   {{- if .Values.host }}
     - host: {{ .Values.host | quote }}
       http:
   {{- else }}
     - http:
   {{- end }}
         paths:
          - path: /
            backend:
              serviceName: {{ .Values.minio.fullnameOverride | quote }}
              servicePort: 9000


