apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ template "fullname" . }}
  namespace: "{{.Release.Namespace}}"
spec:
   rules:
   {{- if .Values.host }}
     - host: {{ .Values.host | quote }}
       http:
   {{- else }}
     - http:
   {{- end }}
         paths:
          - path: /
            backend:
              # this is a way to run minio subchart's template and pass it minio's scope (.Values.minio). 
              # The .Values.minio itself is not sub-scope of the current chart, need to create the dict so it looks like a scope.
              # this way we get the minio fullname, which is the name of the minio service we need to reference here
              serviceName: {{ template "minio.fullname" (dict "Chart" (dict "Name" "minio") "Values" (index .Values "minio") "Release" .Release "Capabilities" .Capabilities) }}
              servicePort: 9000


