apiVersion: v1
kind: Secret
metadata:
  name: sa-secret
type: Opaque
data:
  minioaccesskey: {{ .Values.minio.global.minio.accessKey | b64enc}}
  miniosecretkey: {{ .Values.minio.global.minio.secretKey | b64enc}}

