apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "fullname" . }}-configuration
  namespace: {{ .Values.global.clusterNamespace }}
  imagePullSecret: {{ .Values.global.imagePullSecret }}
data:
  log_level: {{ index .Values.global.log_level .Values.global.env | quote }}
  topicsFindings: {{ .Values.global.topicsFindings | quote }}
  topicsNetflow: {{ .Values.global.topicsNetflow | quote }}
  consumerSupportedDataSources: {{ .Values.global.consumerSupportedDataSources | quote }}
  groupid: {{ .Values.global.groupid | quote }}
{{- if .Values.global.standalone }}
  kafkaMetadataBrokerList: {{ .Values.global.kafkaMetadataBrokerList | quote }}
{{- else }}
  kafkaMetadataBrokerList: {{ .Release.Name}}-kafka-headless:9092
{{- end }}
  kafkaSslCaLocation: {{ .Values.global.kafkaSslCaLocation | quote }}
{{- if .Values.global.kafkaSaslUsername }}
  kafkaSaslUsername: {{ .Values.global.kafkaSaslUsername | quote }}
  kafkaSaslPassword: {{ .Values.global.kafkaSaslPassword | quote }}
{{- end }}
{{- if .Values.global.kafkaSaalMechanism }}
  kafkaSaalMechanism: {{ .Values.global.kafkaSaalMechanism | quote }}
{{- end }}
{{- if .Values.global.kafkaSecurityProtocol }}
  kafkaSecurityProtocol: {{ .Values.global.kafkaSecurityProtocol | quote }}
{{- end }}
{{- if .Values.global.sendQRadar }}
  sendQRadar: {{ .Values.global.sendQRadar | quote }}
{{- else }}
  sendQRadar: 'false'
{{- end }}
{{- if .Values.global.distribFindings }}
  distribFindings: {{ .Values.global.distribFindings | quote }}
{{- else }}
  distribFindings: 'false'
{{- end }}
{{- if .Values.global.distribNeflows }}
  distribNeflows: {{ .Values.global.distribNeflows | quote }}
{{- else }}
  distribNeflows: 'false'
{{- end }}
#qr and qrissuer are required only if sendQRadar is set to true
{{- if .Values.global.qr }}
  qr: {{ .Values.global.qr | quote }}
{{- else }}
  qr: '[]'
{{- end }}
{{- if .Values.global.qrissuer }}
  qrissuer: {{ .Values.global.qrissuer | quote }}
{{- end }}
