apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
 name: {{ template "fullname" . }}
 namespace: {{ .Values.global.clusterNamespace }}
spec:
 podSelector:
  matchLabels:
   microservice: {{ .Values.global.name }}
 ingress:
 - from:
   - namespaceSelector:
       matchLabels:
