apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.global.name }}
  namespace: {{ .Values.global.clusterNamespace }}
  labels:
     microservice: {{ .Values.global.name }}
spec:
   type: ClusterIP
   ports:
   - port: 8080
     targetPort: 8080
   selector:
      microservice: {{ .Values.global.name }}
