---
global:
  # env refers to the environment properties belong to during build-time. Default is "development".
  env: development
  registryNamespace: secadvisor_dev
  name: health-check
  #nameOverride:finding-distributor-qr
  #fullnameOverride:finding-distributor-qr
  tag: 1 
  log_level:
    development: debug
  topicsFindings: 'security_advisor_findings'
  imagePullSecret: 'my-secret'
  kafkaSaalMechanism: 'PLAIN'
  kafkaSecurityProtocol: 'PLAINTEXT' #'SSL'
  #kafkaMetadataBrokerList:'dh-kafka-0.dh-kafka-headless.cert-manager.svc.cluster.local:9092' #local kafka
  #kafkaMetadataBrokerList:'sa-shard-kafka-headless:9092' #'dh-kafka-0.dh-kafka-headless.cert-manager.svc.cluster.local:9092' #local kafka


