---
global:
  # env refers to the environment properties belong to during build-time. Default is "development".
  env: development
  registryNamespace: secadvisor_dev
  name: health-check
  name1: health-check-ingress
  name2: health-check-egress
  #nameOverride:finding-distributor-qr
  #fullnameOverride:finding-distributor-qr
  tag1: 2019-10-3
  tag2: 2019-10-3
  log_level:
    development: debug
  topicsFindings: 'security_advisor_findings'
  repeatAfter: '1m'
  waitForFinding: '1m'
  imagePullSecret: 'my-secret'
  kafkaSaalMechanism: 'PLAIN'
  kafkaSecurityProtocol: 'PLAINTEXT' #'SSL'
  #kafkaMetadataBrokerList:'dh-kafka-0.dh-kafka-headless.cert-manager.svc.cluster.local:9092' #local kafka
  #kafkaMetadataBrokerList:'sa-shard-kafka-headless:9092' #'dh-kafka-0.dh-kafka-headless.cert-manager.svc.cluster.local:9092' #local kafka


