apiVersion: v1
kind: Service
metadata:
  name: {{ template "fullname" . }}-internal-service
  labels:
    app: {{ template "fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"

spec:
  ports:
  - port: 12379
    name: etcd
  - port: 9200
    name: elasticsearch
  selector:
    app: {{ template "fullname" . }}
    tier: analyzer

