---
apiVersion: v1
name: threatanalytics-v2
description: This chart manages the Threat Intelligence Analytics micro-service.
version: 0.0.1
appVersion: 0.0.1
icon: https://avatars.github.ibm.com/u/56137?s=400
maintainers:
- name: Idan Adar
  email: iadar@il.ibm.com
