apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
 name: {{ .Values.global.name }}
 namespace: {{ .Values.global.clusterNamespace }}
spec:
 ingress:
 - from:
   - namespaceSelector:
       matchLabels:
