apiVersion: extensions/v1beta1
kind: Deployment
metadata:
   name: {{ template "fullname" . }}
   namespace: {{ .Values.global.clusterNamespace }}
spec:
   revisionHistoryLimit: 10
   minReadySeconds: 10
   strategy:
      type: RollingUpdate
      rollingUpdate:
         maxUnavailable: 0
         maxSurge: 3
   replicas: 1
   template:
      metadata:
         labels:
            microservice: {{ .Values.global.name }}
      spec:
{{ if .Values.global.serviceAccountName }}
         serviceAccountName: sa-service-account
{{- end }}
         imagePullSecrets:
         - name: {{ .Values.global.imagePullSecret }}
         containers:
         - name: {{ .Values.global.name }}
           image: {{ .Values.global.registry | default "registry.ng.bluemix.net" }}/{{ .Values.global.registryNamespace }}/{{ .Values.global.name }}:{{ .Values.global.tag | default "last" }}
           ports:
           - containerPort: 4443
           env:
           - name: podName
             valueFrom:
               fieldRef:
                 fieldPath: metadata.name
           - name: LOG_LEVEL
             valueFrom:
               configMapKeyRef:
                  name: {{ .Release.Name }}-datacontrol-configuration
                  key: log_level
           - name: statisticsRate
             valueFrom:
               configMapKeyRef:
                  name: {{ .Release.Name }}-datacontrol-configuration
                  key: statisticsRate
           - name: accountsUpdatesTopic
             valueFrom:
               configMapKeyRef:
                  name: {{ .Release.Name }}-datacontrol-configuration
                  key: accountsUpdatesTopic
           - name: accountsUpdatesGroupIdPrefix
             valueFrom:
               configMapKeyRef:
                 name: {{ .Release.Name }}-datacontrol-configuration
                 key: accountsUpdatesGroupIdPrefix
           - name: billingTopic
             valueFrom:
               configMapKeyRef:
                  name: {{ .Release.Name }}-datacontrol-configuration
                  key: billingTopic
           - name: billerCycleDuration
             valueFrom:
               configMapKeyRef:
                  name: {{ .Release.Name }}-datacontrol-configuration
                  key: billerCycleDuration
           - name: billingExpirationTime
             valueFrom:
               configMapKeyRef:
                 name: {{ .Release.Name }}-datacontrol-configuration
                 key: billingExpirationTime
           - name: updateDiscoverersRate
             valueFrom:
               configMapKeyRef:
                  name: {{ .Release.Name }}-datacontrol-configuration
                  key: updateDiscoverersRate
           - name: dataSourcesTopicsMapping
             valueFrom:
               configMapKeyRef:
                  name: {{ .Release.Name }}-datacontrol-configuration
                  key: dataSourcesTopicsMapping
           - name: supportedCollectorIds
             valueFrom:
               configMapKeyRef:
                  name: {{ .Release.Name }}-datacontrol-configuration
                  key: supportedCollectorIds
           - name: supportedRegions
             valueFrom:
               configMapKeyRef:
                 name: {{ .Release.Name }}-datacontrol-configuration
                 key: supportedRegions
           - name: observedEntityIdMaxLength
             valueFrom:
               configMapKeyRef:
                 name: {{ .Release.Name }}-datacontrol-configuration
                 key: observedEntityIdMaxLength
           - name: readStartLimit
             valueFrom:
               configMapKeyRef:
                  name: {{ .Release.Name }}-datacontrol-configuration
                  key: readStartLimit
           - name: readEndLimit
             valueFrom:
               configMapKeyRef:
                  name: {{ .Release.Name }}-datacontrol-configuration
                  key: readEndLimit
           - name: minStreamDiscoveryAttemptPeriod
             valueFrom:
               configMapKeyRef:
                  name: {{ .Release.Name }}-datacontrol-configuration
                  key: minStreamDiscoveryAttemptPeriod
           - name: maxStreamDiscoveryAttemptPeriod
             valueFrom:
               configMapKeyRef:
                  name: {{ .Release.Name }}-datacontrol-configuration
                  key: maxStreamDiscoveryAttemptPeriod
           - name: streamDirHierarchyLevel
             valueFrom:
               configMapKeyRef:
                  name: {{ .Release.Name }}-datacontrol-configuration
                  key: streamDirHierarchyLevel
           - name: maxContinuousObjectDiscoveries
             valueFrom:
               configMapKeyRef:
                  name: {{ .Release.Name }}-datacontrol-configuration
                  key: maxContinuousObjectDiscoveries
           - name: objectSeqNumDigits
             valueFrom:
               configMapKeyRef:
                  name: {{ .Release.Name }}-datacontrol-configuration
                  key: objectSeqNumDigits
           - name: streamDiscoveryAfterSuccessfulObjectDiscoveryPeriod
             valueFrom:
               configMapKeyRef:
                  name: {{ .Release.Name }}-datacontrol-configuration
                  key: streamDiscoveryAfterSuccessfulObjectDiscoveryPeriod
           - name: objectsDiscoveryRate
             valueFrom:
               configMapKeyRef:
                  name: {{ .Release.Name }}-datacontrol-configuration
                  key: objectsDiscoveryRate
           - name: objectMaxNumRecords
             valueFrom:
               configMapKeyRef:
                  name: {{ .Release.Name }}-datacontrol-configuration
                  key: objectMaxNumRecords
           - name: objectMaxNumBytes
             valueFrom:
               configMapKeyRef:
                  name: {{ .Release.Name }}-datacontrol-configuration
                  key: objectMaxNumBytes
           - name: maxAverageBytesPerRecord
             valueFrom:
               configMapKeyRef:
                 name: {{ .Release.Name }}-datacontrol-configuration
                 key: maxAverageBytesPerRecord
           - name: headersMaxLength
             valueFrom:
               configMapKeyRef:
                  name: {{ .Release.Name }}-datacontrol-configuration
                  key: headersMaxLength
           - name: headersPrefix
             valueFrom:
               configMapKeyRef:
                  name: {{ .Release.Name }}-datacontrol-configuration
                  key: headersPrefix
           - name: accountsApiEndpoint
             valueFrom:
               configMapKeyRef:
{{- if .Values.global.standalone }}
                 name: {{ .Release.Name }}-datacontrol-configuration
{{- else }}
                 name: {{ .Release.Name }}-shard-configuration
{{- end }}
                 key: accountsApiEndpoint
           - name: securityAdvisorShardId
             valueFrom:
               configMapKeyRef:
{{- if .Values.global.autoConfig }}
                 name: {{ .Values.global.autoConfigName }}
                 key: shardId
{{- else }}
                 name: {{ .Release.Name }}-datacontrol-configuration
                 key: securityAdvisorShardId
{{- end }}
           - name: accountsApiTimeout
             valueFrom:
               configMapKeyRef:
                 name: {{ .Release.Name }}-datacontrol-configuration
                 key: accountsApiTimeout
           - name: activeDiscovererThreshold
             valueFrom:
               configMapKeyRef:
                 name: {{ .Release.Name }}-datacontrol-configuration
                 key: activeDiscovererThreshold
           - name: statusUpdaterCycleDuration
             valueFrom:
               configMapKeyRef:
                 name: {{ .Release.Name }}-datacontrol-configuration
                 key: statusUpdaterCycleDuration
           - name: accountsInfoWriteUpdatesTopic
             valueFrom:
               configMapKeyRef:
                 name: {{ .Release.Name }}-datacontrol-configuration
                 key: accountsInfoWriteUpdatesTopic
           - name: monitoringPort
             valueFrom:
               configMapKeyRef:
                 name: {{ .Release.Name }}-datacontrol-configuration
                 key: monitoringPort
           - name: collectorSpecificConfig
             valueFrom:
               configMapKeyRef:
                 name: {{ .Release.Name }}-datacontrol-configuration
                 key: collectorSpecificConfig
           - name: produceBillsRate
             valueFrom:
               configMapKeyRef:
                 name: {{ .Release.Name }}-datacontrol-configuration
                 key: produceBillsRate
           - name: streamStartLimit
             valueFrom:
               configMapKeyRef:
                 name: {{ .Release.Name }}-datacontrol-configuration
                 key: streamStartLimit
           - name: streamEndLimit
             valueFrom:
               configMapKeyRef:
                 name: {{ .Release.Name }}-datacontrol-configuration
                 key: streamEndLimit
           - name: objectStartLimit
             valueFrom:
               configMapKeyRef:
                 name: {{ .Release.Name }}-datacontrol-configuration
                 key: objectStartLimit
           - name: objectEndLimit
             valueFrom:
               configMapKeyRef:
                 name: {{ .Release.Name }}-datacontrol-configuration
                 key: objectEndLimit
           - name: handleStreamRate
             valueFrom:
               configMapKeyRef:
                 name: {{ .Release.Name }}-datacontrol-configuration
                 key: handleStreamRate
           - name: cosTimeout
             valueFrom:
               configMapKeyRef:
                 name: {{ .Release.Name }}-datacontrol-configuration
                 key: cosTimeout
           - name: updateDiscoverersMaxOffset
             valueFrom:
               configMapKeyRef:
                 name: {{ .Release.Name }}-datacontrol-configuration
                 key: updateDiscoverersMaxOffset
           - name: accountsAllocationsTopic
             valueFrom:
               configMapKeyRef:
                 name: {{ .Release.Name }}-datacontrol-configuration
                 key: accountsAllocationsTopic
           - name: accountsAllocationsGroupId
             valueFrom:
               configMapKeyRef:
                 name: {{ .Release.Name }}-datacontrol-configuration
                 key: accountsAllocationsGroupId
           - name: accountAllocationExpirationTime
             valueFrom:
               configMapKeyRef:
                 name: {{ .Release.Name }}-datacontrol-configuration
                 key: accountAllocationExpirationTime
           - name: validateAccountsAllocationsRate
             valueFrom:
               configMapKeyRef:
                 name: {{ .Release.Name }}-datacontrol-configuration
                 key: validateAccountsAllocationsRate
           - name: accountInitDelayPeriod
             valueFrom:
               configMapKeyRef:
                 name: {{ .Release.Name }}-datacontrol-configuration
                 key: accountInitDelayPeriod
           - name: sendAccountsAllocationsMessagesRate
             valueFrom:
               configMapKeyRef:
                 name: {{ .Release.Name }}-datacontrol-configuration
                 key: sendAccountsAllocationsMessagesRate
           - name: acquireAccountsAllocationsLockAttemptRate
             valueFrom:
               configMapKeyRef:
                 name: {{ .Release.Name }}-datacontrol-configuration
                 key: acquireAccountsAllocationsLockAttemptRate
           - name: numMockedAccounts
             valueFrom:
               configMapKeyRef:
                 name: {{ .Release.Name }}-datacontrol-configuration
                 key: numMockedAccounts
           - name: cosFindDirectoriesMaxRetries
             valueFrom:
               configMapKeyRef:
                 name: {{ .Release.Name }}-datacontrol-configuration
                 key: cosFindDirectoriesMaxRetries
           - name: refreshAccountsRate
             valueFrom:
               configMapKeyRef:
                 name: {{ .Release.Name }}-datacontrol-configuration
                 key: refreshAccountsRate
           - name: accountsUpdatesCheckRate
             valueFrom:
               configMapKeyRef:
                 name: {{ .Release.Name }}-datacontrol-configuration
                 key: accountsUpdatesCheckRate
           - name: accountsUpdatesCheckMinCycleDuration
             valueFrom:
               configMapKeyRef:
                 name: {{ .Release.Name }}-datacontrol-configuration
                 key: accountsUpdatesCheckMinCycleDuration
           - name: secretKey
             valueFrom:
               configMapKeyRef:
                 name: {{ .Release.Name }}-datacontrol-configuration
                 key: secretKey
           - name: accessKey
             valueFrom:
               configMapKeyRef:
                 name: {{ .Release.Name }}-datacontrol-configuration
                 key: accessKey
           - name: minioRegion
             valueFrom:
               configMapKeyRef:
                 name: {{ .Release.Name }}-datacontrol-configuration
                 key: minioRegion
           - name: minioEndpoint
             valueFrom:
               configMapKeyRef:
                 name: {{ .Release.Name }}-datacontrol-configuration
                 key: minioEndpoint
#### ENVIRONMENT VARIABLES - COMMON CONFIGURATION
           - name: kafkaMetadataBrokerList
             valueFrom:
               configMapKeyRef:
                  name: {{ .Release.Name }}-datacontrol-configuration
                  key: kafkaMetadataBrokerList
           - name: kafkaSslCaLocation
             valueFrom:
               configMapKeyRef:
                  name: {{ .Release.Name }}-datacontrol-configuration
                  key: kafkaSslCaLocation
           - name: redisDbNum
             valueFrom:
               configMapKeyRef:
                  name: {{ .Release.Name }}-datacontrol-configuration
                  key: redisDbNumDC
           - name: iamTokenValidationURL
             valueFrom:
               configMapKeyRef:
                 name: {{ .Release.Name }}-datacontrol-configuration
                 key: iamTokenValidationURL
           - name: iamPDPURL
             valueFrom:
               configMapKeyRef:
                 name: {{ .Release.Name }}-datacontrol-configuration
                 key: iamPDPURL
           - name: iamTokenURL
             valueFrom:
               configMapKeyRef:
                 name: {{ .Release.Name }}-datacontrol-configuration
                 key: iamTokenURL
           - name: iamPAPURL
             valueFrom:
               configMapKeyRef:
                 name: {{ .Release.Name }}-datacontrol-configuration
                 key: iamPAPURL
           - name: kafkaSaalMechanism
             valueFrom:
               configMapKeyRef:
                  name: {{ .Release.Name }}-datacontrol-configuration
                  key: kafkaSaalMechanism
           - name: kafkaSecurityProtocol
             valueFrom:
               configMapKeyRef:
                  name: {{ .Release.Name }}-datacontrol-configuration
                  key: kafkaSecurityProtocol
#### ENVIRONMENT VARIABLES - REDIS SECRETS
           - name: redis_host
             valueFrom:
               configMapKeyRef:
                  name: {{ .Release.Name }}-datacontrol-configuration
                  key: dc_redis_host
           - name: redis_port
             valueFrom:
               configMapKeyRef:
                  name: {{ .Release.Name }}-datacontrol-configuration
                  key: dc_redis_port
           - name: redis_auth
             valueFrom:
               configMapKeyRef:
                  name: {{ .Release.Name }}-datacontrol-configuration
                  key: dc_redis_auth
#### ENVIRONMENT VARIABLES - IAM SECRETS
           - name: iamConfig
             valueFrom:
               configMapKeyRef:
                  name: {{ .Release.Name }}-datacontrol-configuration
                  key: iamConfig
