apiVersion: extensions/v1beta1
kind: Deployment
metadata:
   name: {{ template "fullname" . }}
   namespace: {{ .Values.global.clusterNamespace }}
spec:
   revisionHistoryLimit: 10
   minReadySeconds: 10
   strategy:
      type: RollingUpdate
      rollingUpdate:
         maxUnavailable: 0
         maxSurge: 3
   replicas: 1
   template:
      metadata:
         labels:
            microservice: {{ .Values.global.name }}
      spec:
{{ if .Values.global.serviceAccountName }}
         serviceAccountName: sa-service-account
{{- end }}
         imagePullSecrets:
         - name: {{ .Values.global.imagePullSecret }}
         containers:
         - name: {{ .Values.global.name1 }}
           image: registry.ng.bluemix.net/{{ .Values.global.registryNamespace }}/{{ .Values.global.name1 }}:{{ .Values.global.tag1 | default "last" }}
           ports:
           - containerPort: 443
           env:
           - name: LOG_LEVEL
             valueFrom:
               configMapKeyRef:
                  name: {{ template "fullname" . }}-configuration
                  key: log_level
           - name: repeatAfter
             valueFrom:
               configMapKeyRef:
                  name: {{ template "fullname" . }}-configuration
                  key: repeatAfter
           - name: waitForFinding
             valueFrom:
               configMapKeyRef:
                  name: {{ template "fullname" . }}-configuration
                  key: waitForFinding
           - name: topicsFindings
             valueFrom:
               configMapKeyRef:
                  name: {{ template "fullname" . }}-configuration
                  key: topicsFindings
           - name: kafkaMetadataBrokerList
             valueFrom:
               configMapKeyRef:
                  name: {{ template "fullname" . }}-configuration
                  key: kafkaMetadataBrokerList
           - name: kafkaSaalMechanism
             valueFrom:
               configMapKeyRef:
                  name: {{ template "fullname" . }}-configuration
                  key: kafkaSaalMechanism
           - name: kafkaSecurityProtocol
             valueFrom:
               configMapKeyRef:
                  name: {{ template "fullname" . }}-configuration
                  key: kafkaSecurityProtocol
           - name: kafkaSslCaLocation
             valueFrom:
               configMapKeyRef:
                  name: {{ template "fullname" . }}-configuration
                  key: kafkaSslCaLocation
           - name: clusterNodeIps
             valueFrom:
               configMapKeyRef:
                  name: "skydive-configuration"
                  key: clusterNodeIps
         - name: {{ .Values.global.name2 }}
           image: registry.ng.bluemix.net/{{ .Values.global.registryNamespace }}/{{ .Values.global.name2 }}:{{ .Values.global.tag2 | default "last" }}
           ports:
           - containerPort: 443
           env:
           - name: LOG_LEVEL
             valueFrom:
               configMapKeyRef:
                  name: {{ template "fullname" . }}-configuration
                  key: log_level
           - name: clusterNodeIps
             valueFrom:
               configMapKeyRef:
                  name: skydive-configuration
                  key: clusterNodeIps
           - name: repeatAfter
             valueFrom:
               configMapKeyRef:
                  name: {{ template "fullname" . }}-configuration
                  key: repeatAfter
           - name: waitForFinding
             valueFrom:
               configMapKeyRef:
                  name: {{ template "fullname" . }}-configuration
                  key: waitForFinding
           - name: topicsFindings
             valueFrom:
               configMapKeyRef:
                  name: {{ template "fullname" . }}-configuration
                  key: topicsFindings
           - name: kafkaMetadataBrokerList
             valueFrom:
               configMapKeyRef:
                  name: {{ template "fullname" . }}-configuration
                  key: kafkaMetadataBrokerList
           - name: kafkaSaalMechanism
             valueFrom:
               configMapKeyRef:
                  name: {{ template "fullname" . }}-configuration
                  key: kafkaSaalMechanism
           - name: kafkaSecurityProtocol
             valueFrom:
               configMapKeyRef:
                  name: {{ template "fullname" . }}-configuration
                  key: kafkaSecurityProtocol
           - name: kafkaSslCaLocation
             valueFrom:
               configMapKeyRef:
                  name: {{ template "fullname" . }}-configuration
                  key: kafkaSslCaLocation
