dependencies:
  - name: redis
    version: 6.4.0
    repository: https://kubernetes-charts.storage.googleapis.com
  - name: datacontrol
    version: 0.0.1
    repository: https://github.com/sa-cloud/helm/blob/master/repo?raw=true
  - name: kafka
    version: 0.13.3
    repository: https://kubernetes-charts-incubator.storage.googleapis.com/
  - name: threatanalytics-v2
    version: 0.0.1
    repository: https://github.com/sa-cloud/helm/blob/master/repo?raw=true
  - name: configmgr
    version: 0.0.1
    repository: https://github.com/sa-cloud/helm/blob/master/repo?raw=true
  - name: findingslog
    version: 0.0.1
    repository: https://github.com/sa-cloud/helm/blob/master/repo?raw=true
