---
redis:
  cluster:
    slaveCount: 3
  networkPolicy:
    enabled: false
  master:
    persistence:
      enabled: false
  usePassword: false

kafka:
  persistence:
    enabled: false

datacontrol:
  global:
    # env refers to the environment properties belong to during build-time. Default is "development".
    env: development
    registryNamespace: secadvisor_dev #secadv_dev
    name: datacontrol
    tag: 18 #20 #18 #106 #0.0.106  # 18 is a good working version for unsecure kafka
    imagePullSecret: 'my-secret'
    statisticsRate: '60000'
    dataSourcesTopicsMapping: '{"netflow_ingress":"netflow_ingress","netflow_egress":"netflow_egress","netflow_internal":"netflow_internal","netflow_other":"netflow_other","at_cadf":"at_cadf"}'
    supportedRegions: 'us-south,us-east,us-west,eu-gb,eu-de,au-syd,jp-tok,other,dontcare'
    accountsApiEndpoint: 'configmgr:443/api/v1/'
    securityAdvisorShardId: 'default_449a6a22-1059-4b96-97cb-0f0dca2d25f3'
    redisDbNum: 1
    redisDbNumDC: 1
    # must match minio.minioConfig.region 
    minioRegion: 'dontcare'
    # must match the access key of the secret defined in minio.existingSecret 
    accessKey: 'admin'
    # must match the secret key of the secret defined in minio.existingSecret 
    secretKey: 'admin1234'
    #'PLAIN' and 'PLAINTEXT' make kafka run in unsecure mode
    kafkaSaalMechanism: 'PLAIN'
    kafkaSecurityProtocol: PLAINTEXT #'SSL'
    kafkaSslTruststoreLocation: certs/
    kafkaSslTruststorePassword: test1234
    # Don't change this value. false means this is a combined helm (redis and minio are subcharts here)
    standalone: false
    #fixed redis port. No need to change this.
    dc_redis_port: '6379'
    # all of the iam configurations are irrelevant in icp, must be set only when installing on bluemix
    iamTokenValidationURL: 'https://iam.test.cloud.ibm.com/identity/keys'
    iamPDPURL: 'https://iam.test.cloud.ibm.com'
    iamTokenURL: 'https://iam.test.cloud.ibm.com/identity/token'
    iamPAPURL: 'https://iam.test.cloud.ibm.com'
    iamConfig: '{"adminService":{"serviceName":"Grafeas-Admin-Service","serviceid":"ServiceId-1d1e8188-8ae6-45a4-b67e-5058a8373638"},"externalService":{"apiKey":"pYgIUhpGO25tN52EtbuzzomqGX_D7h_La8PCD_ELj6cq","serviceName":"Grafeas-External-Service","serviceid":"ServiceId-838121e1-8053-40e0-85d6-43a7d30f110d"},"internalService":{"apiKey":"ZSbLcYWa3iLul8zI4Vc_7tgYN8qG8GF4qmcaFL79713-","serviceName":"Grafeas-Internal-Service","serviceid":"ServiceId-5f4ca4ac-9a64-4bf0-ae03-4ad9a21afe42"},"serviceCname":"staging","viewerService":{"apiKey":"pYgIUhpGO25tN52EtbuzzomqGX_D7h_La8PCD_ELj6cq","serviceName":"security-advisor","serviceid":"ServiceId-838121e1-8053-40e0-85d6-43a7d30f110d"}}'

threatanalytics-v2:
  global:
    # env refers to the environment properties belong to during build-time. Default is "development".
    env: development

    # Threat Intelligence Analytics micro-service properties.
    name: tia
    registryNamespace: secadvisor_dev
    tag: 6 #7 # 6 # 6 is a good stable version for unsecured kafka
    imagePullSecret: 'my-secret'
    consumerGroupId: 'tia-consumer-group-dev'
    consumerTopics: 'netflow_ingress,netflow_egress'
    consumerSupportedDataSources: 'netflow_ingress,netflow_egress'
    consumerRequiredAnalytic: 'tia'
    xfeDbObjectUrl: 'https://s3-api.us-geo.objectstorage.softlayer.net/xfe-ipr-db-1725631/xfe_ipr_db.gz'
    xforceUrlLink: 'https://exchange.xforce.ibmcloud.com/'
    standalone: false
    redis_port: '6379'
    redisDbNum: '2'
    minioRegion: 'dontcare'
    accessKey: 'admin'
    secretKey: 'admin1234'
    useOS: 'minio'
    xfeDbCosIamConfig: '{"iamTokenURL":"https://iam.bluemix.net/identity/token","iamPDPURL":"https://iam.bluemix.net","iamPAPURL":"https://iam.bluemix.net","iamPublicKeysEndpoint":"https://iam.bluemix.net/identity/keys","serviceCname":"TIA-XFE-COS","adminService":{"apiKey":"stlUyXu1a4HOsA57sRSgeFouqbcWbMuB-EWbufrMghdv","serviceName":"TIA-XFE-COS","serviceid":"TIA-XFE-COS"},"externalService":{"apiKey":"stlUyXu1a4HOsA57sRSgeFouqbcWbMuB-EWbufrMghdv","serviceName":"TIA-XFE-COS","serviceid":"TIA-XFE-COS"},"internalService":{"apiKey":"stlUyXu1a4HOsA57sRSgeFouqbcWbMuB-EWbufrMghdv","serviceName":"TIA-XFE-COS","serviceid":"TIA-XFE-COS"},"viewerService":{"apiKey":"stlUyXu1a4HOsA57sRSgeFouqbcWbMuB-EWbufrMghdv","serviceName":"TIA-XFE-COS","serviceid":"TIA-XFE-COS"}}'
    #'PLAIN' and 'PLAINTEXT' make kafka run in unsecure mode
    kafkaSaalMechanism: 'PLAIN'
    kafkaSecurityProtocol: PLAINTEXT #'SSL'
    kafkaSslTruststoreLocation: certs/
    kafkaSslTruststorePassword: test1234

configmgr:
  global:
    # env refers to the environment properties belong to during build-time. Default is "development".
    env: development
    registryNamespace : secadvisor_dev
    name: configmgr
    tag: 1
    shardId: 'default_449a6a22-1059-4b96-97cb-0f0dca2d25f3'
    shardData: '{"accounts":[{"account_id":"test123","bucket_url":"sa-icp:9000/icptest","region":"dontcare","accessKey":"admin","secretKey":"admin1234","collect_from":{"netflow_ingress":true,"netflow_egress":true,"netflow_internal":true,"netflow_other":true,"at_cadf":true},"sa_analytics":{"tia":true,"ata":true,"nba":true}, "sa_instance_crn":"crn:v1:staging:public:security-advisor:us-south:a/d0c8a917589e40076961f56b23056d16:ef71b41c-3239-5ff0-ad6e-5f8059f1130b:security-advisor:", "sa_analytics_status":{"ata":[{"packageUrl":"https://","num_active_rules":2,"num_dormant_rules":45,"num_illegal_rules":6,"status":"success"}],"dc":{"num_sources_netflow":3,"num_sources_at":1}}}]}'
