---
## Architecture metadata
arch:
  __metadata:
    label: "analyzer node architecture scheduling preferences"
    description: "Analyzer node architecture to deploy to."
  amd64:
    __metadata:
      name: "amd64"
      label: "amd64"
      description: "Architecture preference for target worker node."
      type: "string"
      immutable: false
      required: true
      options:
        - label: "0 - Do not use"
          value: "0 - Do not use"
        - label: "1 - Least preferred"
          value: "1 - Least preferred"
        - label: "2 - No preference"
          value: "2 - No preference"
        - label: "3 - Most preferred"
          value: "3 - Most preferred"

  ppc64le:
    __metadata:
      name: "ppc64le"
      label: "ppc64le"
      description: "Architecture preference for target worker node."
      type: "string"
      immutable: false
      required: true
      options:
        - label: "0 - Do not use"
          value: "0 - Do not use"
        - label: "1 - Least preferred"
          value: "1 - Least preferred"
        - label: "2 - No preference"
          value: "2 - No preference"
        - label: "3 - Most preferred"
          value: "3 - Most preferred"

  s390x:
    __metadata:
      name: "s390x"
      label: "s390x"
      description: "Architecture preference for target worker node."
      type: "string"
      immutable: false
      required: true
      options:
        - label: "0 - Do not use"
          value: "0 - Do not use"
        - label: "1 - Least preferred"
          value: "1 - Least preferred"
        - label: "2 - No preference"
          value: "2 - No preference"
        - label: "3 - Most preferred"
          value: "3 - Most preferred"

## Image metadata
image:
  __metadata:
    label: "Docker image configuration"
  repository:
    __metadata:
      name: "repository"
      label: "repository"
      description: "Docker image location"
      type: "string"
      immutable: false
      required: true
  tag:
    __metadata:
      name: "Tag"
      label: "Image tag"
      description: "The docker image tag / version"
      type: "string"
      immutable: false
      required: true
  secretName:
    __metadata:
      name: "Image Pull Secret Name"
      label: "Image Pull Secret Name"
      description: "Image Pull Secret Name. for more information, see 'Add ImagePullSecrets to a service account' kubernetes documentation"
      type: "string"
      immutable: false
      required: false
  imagePullPolicy:
    __metadata:
      name: "Image pull policy"
      label: "Image pull policy"
      description: "Docker image pull policy"
      type: "string"
      immutable: false
      required: true

## Resources metadata
resources:
  __metadata:
    label: "Resources"
    description: "Limit resources to the chart."
  requests:
    cpu:
      __metadata:
        label: "CPU request"
        description: "The requested CPU"
        type: "string"
        required: true
    memory:
      __metadata:
        label: "Memory request"
        description: "The memory request"
        type: "string"
        required: true
  limits:
    cpu:
      __metadata:
        label: "CPU limit"
        description: "The CPU limit"
        type: "string"
        required: true
    memory:
      __metadata:
        label: "Memory limit"
        description: "The memeory limit"
        type: "string"
        required: true


service:
  __metadata:
    label: "service"
    description: "How to expose skydive web analyzer interface to the user."
  name:
    __metadata:
      name: "Name"
      label: "Service Name"
      description: "This is the Service Name"
      type: "string"
      immutable: false
      required: true
      validation: "^[a-zA-Z]([a-zA-Z0-9-\\.])+$"
  port:
    __metadata:
      name: "port"
      label: "Service port"
      description: "This is the service port number"
      type: "number"
      immutable: false
      required: true
  type:
    __metadata:
      name: "type"
      label: "Service port type"
      description: "This is the service port type (e.g. NodePort, LoadBalancer)"
      type: "string"
      immutable: false
      required: true
      options:
        - label: "Cluster IP"
          value: "ClusterIP"
        - label: "Node Port"
          value: "NodePort"
        - label: "Load Balancer"
          value: "LoadBalancer"

analyzer:
  __metadata:
    label: "Analyzer Topology"
    description: "Assist skydive understand the network."
  topology:
    fabric:
      __metadata:
        name: "Fabric"
        label: "Analyzer Topology Fabric"
        description: "This represents the network fabric in .dot language format ref: https://github.com/skydive-project/skydive/blob/master/etc/skydive.yml.default"
        type: "string"
        immutable: false
        required: true

## Persistence options
persistence:
  __metadata:
    label: "Data persistence configuration"
    description: "The nature of the dataVolume persistent."
  enabled:
    __metadata:
      name: "enabled"
      label: "Enable persistence for this deployment"
      description: "Enables persistence for this deployment."
      type: "boolean"
      immutable: false
      required: true
  useDynamicProvisioning:
    __metadata:
      name: "useDynamicProvisioning"
      label: "Use dynamic provisioning for persistent volume"
      description: "If dynamic provisioning is available in the cluster this option will automatically provision the requested volume if set to true."
      type: "boolean"
      immutable: false
      required: true

## Data volume claim options
dataVolume:
  __metadata:
    label: "Data volume configuration"
    description: "Data volume stores ElasticSearch information on the metadata associated with the deployed network."
  name:
    __metadata:
      name: "datavolume"
      label: "Name of the persistent volume claim"
      description: "By default a persistent volume claim will be created with this name."
      type: "string"
      immutable: false
      required: true
  existingClaimName:
    __metadata:
      name: "existingClaimName"
      label: "Existing volume claim"
      description: "By default a new persistent volume claim will be created. Specify an existing claim here if one is available."
      type: "string"
      immutable: false
      required: false
  storageClassName:
    __metadata:
      name: "storageClassName"
      label: "Existing storage class name"
      description: "Choose a specific storage class name. Defaults to the default storage class in the cluster."
      type: "string"
      immutable: false
      required: false
  size:
    __metadata:
      name: "size"
      label: "Size of the volume claim"
      description: "Defaults to 20Gi of storage request. Choose a different size of disk if needed."
      type: "string"
      immutable: false
      required: true

## Storage (Skydive Analyzer options)
storage:
  __metadata:
    label: "Controls on data retention"
    description: "Upper limits on records and indexes."
  flows:
    indicesToKeep:
      __metadata:
        name: "flows_indicesToKeep"
        label: "Indices to keep"
        description: "This is the number of indices that will be kept in elasticsearch to persist flows data"
        type: "number"
        immutable: false
        required: true
    indexEntriesLimit:
      __metadata:
        name: "flows_indexEntriesLimit"
        label: "Index entries limit"
        description: "This is the number of records that will be kept per index in elasticsearch to persist flows data"
        type: "number"
        immutable: false
        required: true
  topology:
    indicesToKeep:
      __metadata:
        name: "topology_indicesToKeep"
        label: "Indices to keep"
        description: "This is the number of indices that will be kept in elasticsearch to persist topology data"
        type: "number"
        immutable: false
        required: true
    indexEntriesLimit:
      __metadata:
        name: "topology_indexEntriesLimit"
        label: "Index entries limit"
        description: "This is the number of records that will be kept per index in elasticsearch to persist topology data"
        type: "number"
        immutable: false
        required: true
