---
apiVersion: v1
name: configmgr
description: This chart manages the Data Control micro-service.
version: 0.0.1
appVersion: 0.0.1
icon: https://avatars.github.ibm.com/u/56137?s=400
maintainers:
- name: Ashish K Thakur
  email: ashishth@in.ibm.com
