---
#uncomment this when installing on IKS, and set the host value to cluster's ingress-subdomain
#host: "customerv11.us-south.containers.appdomain.cloud"
minio:
  accessKey: "admin"
  secretKey: "admin1234"
  #this will be used as the chart name in the convention releasename-chartname
  nameOverride: "minio"
  #this will be used as the chart name and used as is for the components naming
  #fullnameOverride:sa-collect-minio-object-store
  ingress:
    enabled: false
    path: "/"
    hosts: []
  persistence:
    enabled: false
  # minioConfig values are used by minio server the values will be passed on to Minio container(s) when Chart is deployed
  #https://docs.min.io/docs/minio-server-configuration-guide.html
  minioConfig:
    region: "dontcare"
  defaultBucket:
    enabled: true
    name: icptest

global:
    secAdv: true
    dockerRuntime: true
    registryNamespace: secadvisor_dev #secadv_dev
    imagePullSecret: 'my-secret'
    preinstallJobImage: 'sa-preinstall-job'
    preinstallJobTag: 8

ibm-skydive-dev:
  image:
    repository: cognetive/skydive
    tag: 2019.04.16___08.35
    # tag for older k8s version (i.e ICP)
    tagVdocker: amd64-latest
  env:
    # For debug purposes
    - name: SKYDIVE_LOGGING_LEVEL
      value: "INFO"

    # Send flow information to defender back-end
    - name: SKYDIVE_ANALYZER_FLOW_BACKEND
      value: "defender"

    # We do not propagate the topology information, so just keep this in memory (this is being deleted over time)
    - name: SKYDIVE_ANALYZER_TOPOLOGY_BACKEND
      value: "memory"

    # Maximum number of flows per object
    - name: SKYDIVE_STORAGE_DEFENDER_MAX_FLOWS_PER_OBJECT
      value: "60000"

    # Flows to be updated every 30 seconds (thus, every 60 seconds to defender)
    - name: SKYDIVE_FLOW_UPDATE
      value: "30"

    # Maximum seconds per object
    - name: SKYDIVE_STORAGE_DEFENDER_MAX_SECONDS_PER_OBJECT
      value: "60"

    # Maximum seconds per stream
    - name: SKYDIVE_STORAGE_DEFENDER_MAX_SECONDS_PER_STREAM
      value: "86400"

    # Object-storage region
    - name: SKYDIVE_STORAGE_DEFENDER_REGION
      value: "dontcare"

    # ?
    - name: SKYDIVE_STORAGE_DEFENDER_DRIVER
      value: defender

    # COLLECTION (as defined in the defender API)
    - name: SKYDIVE_STORAGE_DEFENDER_COLLECTION
      value: "netflow"

    # ANALYZER_STARTUP_CAPTURE_GREMLIN invoke at startup capturing in selected nodes
    - name: SKYDIVE_ANALYZER_STARTUP_CAPTURE_GREMLIN
      value: "G.V().has('Name', NE('lo'))"

    - name: SKYDIVE_ANALYZER_STARTUP_CAPTURE_BPF
      value: "not (tcp dst port 8082 or tcp dst port 9000)"

    - name: SKYDIVEX_AGENT_CAPTURE_SYN
      value: "True"

    # DEFAULT_LAYER_KEY_MODE - the layers used to identify a unique flow.
    - name: SKYDIVE_FLOW_DEFAULT_LAYER_KEY_MODE
      value: "L3"

    - name: SKYDIVE_ANALYZER_STARTUP_CAPTURE_TYPE
      value: "pcap"

    - name: SKYDIVE_AGENT_CAPTURE_SYN
      value: "True"

