---
global:
  # env refers to the environment properties belong to during build-time. Default is "development".
  env: development
  registryNamespace: secadvisor_dev
  name: findingslog
  #nameOverride:finding-distributor-qr
  #fullnameOverride:finding-distributor-qr
  #7 is working local logger version #11 is log/qradar distribution by sendQRadar #16 supports also netflow sending #17 is qr json instead of single qrip+qrport
  tag: 18 
  log_level:
    development: debug
  topicsFindings: 'security_advisor_findings'
  topicsNetflow: 'netflow_ingress,netflow_egress'
  consumerSupportedDataSources: 'netflow_ingress,netflow_egress'
  groupid: 'findingslog-'
  imagePullSecret: 'my-secret'
  sendQRadar: 'false' # set false for simple local log distributor; if set to true, qr parameter must be set
  distribFindings: 'true'
  distribNeflows: 'false'
  qrissuer: 'csaInsights'
  #qrissuer:'csaNetflows'
  qr: '[{"ip":"iris-bluesecure.sl.cloud9.ibm.com","port":514},{"ip":"52.117.58.153","port":514},{"ip":"86.4.79.222","port":12514}]'
  kafkaSaalMechanism: 'PLAIN'
  kafkaSecurityProtocol: 'PLAINTEXT' #'SSL'
  #standalone:true #uncommenting this option required setting the kafkaMetadataBrokerList value
  #kafkaMetadataBrokerList:'dh-kafka-0.dh-kafka-headless.cert-manager.svc.cluster.local:9092' #local kafka
  #kafkaMetadataBrokerList:'sa-shard-kafka-headless:9092' #'dh-kafka-0.dh-kafka-headless.cert-manager.svc.cluster.local:9092' #local kafka


