---
global:
  # env refers to the environment properties belong to during build-time. Default is "development".
  env: development
  registryNamespace: secadvisor_dev
  name: findingslog
  nameOverride: finding-distributor-qr
  fullnameOverride: finding-distributor-qr
  tag: 12 #7 is working local logger version #11 is log/qradar distribution by sendQRadar #12 supports also netflow sending
  log_level:
    development: debug
  topicsFindings: 'security_advisor_findings'
  topicsNetflow: 'netflow_ingress,netflow_egress'
  consumerSupportedDataSources: 'netflow_ingress,netflow_egress'
  groupid: 'findingslog'
  imagePullSecret: 'my-secret'
  sendQRadar: 'true' # set false for simple local log distributor
  distribFindings: 'false'
  distribNeflows: 'true'
  qrip: 'iris-bluesecure.sl.cloud9.ibm.com'
  qrport: 514
  qrissuer: 'csaInsights'
  kafkaSaalMechanism: 'PLAIN'
  kafkaSecurityProtocol: 'PLAINTEXT' #'SSL'
  #kafkaMetadataBrokerList:'dh-kafka-0.dh-kafka-headless.cert-manager.svc.cluster.local:9092' #local kafka
  kafkaMetadataBrokerList: 'sa-shard-kafka-headless:9092' #'dh-kafka-0.dh-kafka-headless.cert-manager.svc.cluster.local:9092' #local kafka


